#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XTreme_Travel.Resource", IsApplication=true)]

namespace XTreme_Travel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_dialog_noactionbar_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int login_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int plus = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnDialogEmail = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int buttonLogout = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int buttonSignIn = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int buttonSignUp = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int buttonUser = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int demoImageView = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout2 = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int textInfo = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int textOptional = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int txtCurrentTrip = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int txtDate = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int txtEmail = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int txtFirstName = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int txtLastName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int txtNation = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int txtPassword = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int txtSettings = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int txtSettingsAp = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int txtSync = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_user_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenu = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
